services:
  # Dolibarr ERP/WMS
  dolibarr:
    image: tuxgasy/dolibarr:14
    container_name: dolibarr
    ports:
      - "8080:80"   # 80 → 8080 pour éviter le conflit
    environment:
      - DOLI_DB_HOST=dolibarr-mariadb
      - DOLI_DB_USER=epitech
      - DOLI_DB_PASSWORD=epitech13
      - DOLI_DB_NAME=dolibarr
      - DOLI_URL_ROOT=http://localhost:8080
      - PHP_INI_DATE_TIMEZONE=Europe/Paris
    depends_on:
      - dolibarr-mariadb
    restart: unless-stopped

  # MariaDB
  dolibarr-mariadb:
    image: mariadb:latest
    container_name: dolibarr-mariadb
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=epitech13
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=epitech
      - MYSQL_PASSWORD=epitech13
    restart: unless-stopped

  # PHPMyAdmin
  dolibarr-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dolibarr-phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=dolibarr-mariadb
      - PMA_PORT=3306
      - PMA_USER=epitech
      - PMA_PASSWORD=epitech13
    depends_on:
      - dolibarr-mariadb
    restart: unless-stopped

volumes:
  data:
